version: '3.8'  

services:  
  bot:
    container_name: bot
    build: .  
    image: telegram-bot  
    env_file:  
      - .env  
    volumes:  
      - ./:/app  # Точное монтирование
      - /tmp:/tmp         # Для системных сокетов
    restart: unless-stopped
    # Опциональные улучшения  
    stdin_open: true  
    tty: true


